version: 2
jobs:
  build:
    docker:
      - image: swift:3.1.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: ""
    steps:
      - run: apt-get update -yq && apt-get install -yq libpq-dev
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test
